/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PoG
 */
public class application1 extends javax.swing.JFrame {

    /**
     * Creates new form application1
     */
    public application1() {
        initComponents();
     
        jAnswerArea.setEditable(false);  //this makes text area uneditable. 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNumber1 = new javax.swing.JTextField();
        jNumber2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAnswerArea = new javax.swing.JTextArea();
        jExponential = new javax.swing.JRadioButton();
        jGCD = new javax.swing.JRadioButton();
        jFactorial = new javax.swing.JRadioButton();
        jPower10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Number 1");

        jLabel2.setText("Number 2");

        jNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumber1ActionPerformed(evt);
            }
        });

        jNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumber2ActionPerformed(evt);
            }
        });

        jAnswerArea.setColumns(20);
        jAnswerArea.setRows(5);
        jScrollPane1.setViewportView(jAnswerArea);

        jExponential.setText("Exponential");
        jExponential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExponentialActionPerformed(evt);
            }
        });

        jGCD.setText("GCD");
        jGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGCDActionPerformed(evt);
            }
        });

        jFactorial.setText("Factorial");
        jFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFactorialActionPerformed(evt);
            }
        });

        jPower10.setText("Power 10");
        jPower10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPower10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jExponential, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jGCD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPower10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumber1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNumber2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExponential)
                    .addComponent(jGCD)
                    .addComponent(jFactorial)
                    .addComponent(jPower10))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumber1ActionPerformed
      System.out.println(jNumber1.getText());
        
      
      
      
    }//GEN-LAST:event_jNumber1ActionPerformed

    private void jNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumber2ActionPerformed
      System.out.println(jNumber2.getText());
      
      
      
    }//GEN-LAST:event_jNumber2ActionPerformed

    private void jExponentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExponentialActionPerformed
        
     
       int answer = Exponential.exponential(Integer.parseInt(jNumber1.getText()),Integer.parseInt(jNumber2.getText()));
       jAnswerArea.setText(String.valueOf(answer));
        

    }//GEN-LAST:event_jExponentialActionPerformed

    private void jGCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGCDActionPerformed
         
        int answer = gcd.GCD(Integer.parseInt(jNumber1.getText()),Integer.parseInt(jNumber2.getText()));
       jAnswerArea.setText(String.valueOf(answer));
        
    }//GEN-LAST:event_jGCDActionPerformed

    private void jFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFactorialActionPerformed
        long answer = Factorial.factorial(Long.parseLong(jNumber1.getText()));
       jAnswerArea.setText(String.valueOf(answer));
    }//GEN-LAST:event_jFactorialActionPerformed

    private void jPower10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPower10ActionPerformed
       int answer = Power.place(Integer.parseInt(jNumber1.getText()),1);
       jAnswerArea.setText(String.valueOf(answer));
    }//GEN-LAST:event_jPower10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(application1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(application1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(application1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(application1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new application1().setVisible(true);
            }
        });
    }

  /*  public int exponential(int base, int pow){
       if(pow<1)
        {
            return 1;}
       
       else 
        {   
           return base*exponential(base, pow-1);
           }
       //recursive call.
    }    */
    
 /*   public int GCD (int num1, int num2) {
        
        if (num2 != 0)
            return GCD(num2, num1 % num2);
        else
            return num1;

    } */
/* public long factorial (long n)
	{
		long fact;
		fact = 1;
		while (n > 0)
		{
			fact = fact * n;
			n = n - 1;
		}
                return fact;

        }  */
/* public int place (int num, int pow) 
 {
     if (num < pow){
         return pow;
     }
     return place(num, pow*10);
        
        
     
 }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAnswerArea;
    private javax.swing.JRadioButton jExponential;
    private javax.swing.JRadioButton jFactorial;
    private javax.swing.JRadioButton jGCD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNumber1;
    private javax.swing.JTextField jNumber2;
    private javax.swing.JRadioButton jPower10;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
