/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment4;

/**
 *
 * @author PoG
 */
public class Graph extends javax.swing.JFrame {
            
    public DRG graph;
  
    // *
    // *
    public Graph() {
        initComponents();
        
		graph = new DRG(50);
		//init in paddies program
		Node atlanta = new Node("Atlanta"); 
		Node austin =  new Node("Austin");
		Node chicago = new Node("Chicago");
		Node dallas = new Node("Dallas");
		Node denver = new Node("Denver");
		Node houston = new Node("Houston");
		Node washington = new Node("Washington");
			
		graph.addVertex(atlanta);
		graph.addVertex(austin);
		graph.addVertex(chicago);
		graph.addVertex(dallas);
		graph.addVertex(denver);
		graph.addVertex(houston);
		graph.addVertex(washington);
			
		graph.addEdge(atlanta, houston, 800);
		
		graph.addEdge(atlanta, washington, 600);
		
		graph.addEdge(austin, dallas, 200);
		
		graph.addEdge(austin, houston, 160);
		
		graph.addEdge(chicago, denver, 1000);
		
		graph.addEdge(dallas, austin, 200);
                
                graph.addEdge(dallas, chicago, 900);
                
                graph.addEdge(dallas, denver, 780);
                
                graph.addEdge(denver, atlanta, 1400);
                
                graph.addEdge(denver, chicago, 1000);
                
                graph.addEdge(houston, atlanta, 800);
                
                graph.addEdge(washington, atlanta, 600);
                
                graph.addEdge(washington, dallas, 1300);
                
                
		
	        FlightScheduleField.setText(graph.displayAllFlights());
                
		
			
	}	


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DepartureAirportTextField = new javax.swing.JTextField();
        ArrivalAirportTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DistanceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightScheduleField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightInformationField = new javax.swing.JTextArea();
        AddNewFlightButton = new javax.swing.JButton();
        SeekFlightButton = new javax.swing.JButton();
        DeleteFlightButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Departure Airport");

        jLabel2.setText("Arrival Airport");

        DepartureAirportTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureAirportTextFieldActionPerformed(evt);
            }
        });

        ArrivalAirportTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivalAirportTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Distance");

        DistanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanceTextFieldActionPerformed(evt);
            }
        });

        FlightScheduleField.setColumns(20);
        FlightScheduleField.setRows(5);
        jScrollPane1.setViewportView(FlightScheduleField);

        FlightInformationField.setColumns(20);
        FlightInformationField.setRows(5);
        jScrollPane2.setViewportView(FlightInformationField);

        AddNewFlightButton.setText("Add New Flight");
        AddNewFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewFlightButtonActionPerformed(evt);
            }
        });

        SeekFlightButton.setText("Seek Flight");
        SeekFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeekFlightButtonActionPerformed(evt);
            }
        });

        DeleteFlightButton.setText("Delete Flight");
        DeleteFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFlightButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepartureAirportTextField)
                            .addComponent(ArrivalAirportTextField)
                            .addComponent(DistanceTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddNewFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(SeekFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DepartureAirportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ArrivalAirportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(DistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeekFlightButton)
                    .addComponent(DeleteFlightButton)
                    .addComponent(ExitButton))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepartureAirportTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureAirportTextFieldActionPerformed
          
    }//GEN-LAST:event_DepartureAirportTextFieldActionPerformed

    private void AddNewFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewFlightButtonActionPerformed
        
       FlightInformationField.setText(graph.addEdge(new Node(DepartureAirportTextField.getText()),new Node(ArrivalAirportTextField.getText()),Integer.parseInt(DistanceTextField.getText())));
       FlightScheduleField.setText(graph.displayAllFlights());
    }//GEN-LAST:event_AddNewFlightButtonActionPerformed

    private void SeekFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeekFlightButtonActionPerformed
              FlightInformationField.setText(graph.depthFirstSearch(graph,new Node(DepartureAirportTextField.getText()),new Node(ArrivalAirportTextField.getText())));
    }//GEN-LAST:event_SeekFlightButtonActionPerformed

    private void DeleteFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFlightButtonActionPerformed
     FlightInformationField.setText(graph.deleteEdge(new Node(DepartureAirportTextField.getText()),new Node(ArrivalAirportTextField.getText())));
       FlightScheduleField.setText(graph.displayAllFlights()); 
    }//GEN-LAST:event_DeleteFlightButtonActionPerformed

    private void ArrivalAirportTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivalAirportTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrivalAirportTextFieldActionPerformed

    private void DistanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceTextFieldActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewFlightButton;
    private javax.swing.JTextField ArrivalAirportTextField;
    private javax.swing.JButton DeleteFlightButton;
    private javax.swing.JTextField DepartureAirportTextField;
    private javax.swing.JTextField DistanceTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextArea FlightInformationField;
    private javax.swing.JTextArea FlightScheduleField;
    private javax.swing.JButton SeekFlightButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    

}

